name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the bug report! We'd appreciate if you have checked that you are reporting a new issue.
        If you've found a duplicate, be sure to add a reaction/emoji to there instead. We'll try to prioritize
        critical / most-wanted issues.

        If you would like to obtain support (not reporting a bug), please visit https://wiki.ultramarine-linux.org/en/community/community/.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Summarize the bug and describe what you've expected.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Tell us how we can find this issue by performing a series of steps. You are encouraged to attach screenshots and logs.
      placeholder: |
        1. Pets the computer
        2. Meows 9 times consecutively
        3. Watch the computer freeze
    validations:
      required: true
  - type: textarea
    id: sol
    attributes:
      label: Possible Solutions
      description: Describe a possible solution
  - type: input
    id: version
    attributes:
      label: Release Version
      description: The numerical value that represents the version of Ultramarine Linux you're using.
      placeholder: 40
    validations:
      required: true
  - type: dropdown
    id: edition
    attributes:
      label: Edition / Desktop Environment / Hardware
      description: Choose the DEs you've reproduced this issue on.
      multiple: true
      options:
        - Flagship/Budgie
        - KDE Plasma
        - GNOME
        - XFCE
        - Chromebook (x86_64)
        - Raspberry Pi
        - ARM machines in general
        - Others (Please specify in Summary)
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please select checkboxes that describe your system and this issue.
      options:
        - label: I've checked for duplicates in this repository. (not required)
        - label: I'm using the immutable/atomic version. (i.e. I think this issue might be specific to immutable.)
        - label: This issue is not reproducible on Fedora Linux.
        - label: This issue is not reproducible on other Linux distros.
